### ISSUE TITLE
Running prepare twice, a second bootstrap-group is created

### ISSUE THREAD

**Issue by sdorheim** [cognitedata/inso-bootstrap-cli#11]

**Comment by spex66** [comment]
thx for reporting @sdorheim, 
not made this step idempotent, will look into it

**Comment by spex66** [comment]
@sdorheim works for me now with the branch / PR from #12 
- some other small improvements where made too

next steps:

1. you can comment on the PR (if you want)
2. it would be great if you can check out the branch and repeat your test to confirm the fix?
3. it should cleanup your falsely created multiple `cdf:boostraps` from pior runs by running it again too

Waiting on your response, so that I can decide when we can merge to next release which will be `v1.3.0`
FYI: I have an internal problem to check tomorrow about the failing gh-checks

**Comment by spex66** [comment]
Changes tested and merged.
Thx @sdorheim for you report and support!

new tag is `v1.3.0`
